### PR TITLE
Update Computers.jsx

### PR DESCRIPTION
**Pull request by Jamill-hallak**
fix Not finding ./desktop_pc/scene.gltf

### CODE REVIEW

**Comment by Jamill-hallak** [comment]
https://github.com/adrianhajdin/project_3D_developer_portfolio/issues/40

**Comment by locodis** [comment]
scene.gltf has two errors __>> ??

**Comment by Jamill-hallak** [comment]
what are the errors ?

**Comment by locodis** [comment]
ı dont know that ı m look ing after :)
i gave up because of that

**Pull request merged**
